# Generated by Django 3.2.9 on 2021-12-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='realm_id',
            field=models.IntegerField(default=4455),
        ),
    ]
