# Generated by Django 3.2.9 on 2021-12-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('category', models.CharField(max_length=100)),
                ('media', models.URLField()),
                ('followed_by', models.ManyToManyField(related_name='followed_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_id', models.BigIntegerField(db_index=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('realm_id', models.IntegerField()),
                ('auctioned_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
